import { LOYALTY_PROGRAM_ADDRESS, LOYALTY_TOKEN_ADDRESS } from "./address";
import { LOYALTY_PROGRAM_ABI, LOYALTY_TOKEN_ABI } from "./abi";

export {
	LOYALTY_PROGRAM_ADDRESS,
	LOYALTY_TOKEN_ADDRESS,
	LOYALTY_PROGRAM_ABI,
	LOYALTY_TOKEN_ABI,
};
